### Settings for the Production Instance RCS3 
---
#@@@@ The following MUST be localized to the AWS Account @@@@ 
profile: "291988307276_AWSAdministratorAccess"
accountid: "291988307276"
region: "us-west-2"

# 1. Where bucket postfixes where backups and inventories are stored
#    policy postfix
bucket_postfix: "uci-p-bkup-bucket"
inventory_postfix: "uci-p-inventory"
policy_postfix: "uci-bkup-policy"

# 2. The name of the storage lens bucket 
lensbucket: "rcs3-pane-uci-p-report"
lens: "rcs3-pane"

# 3. The name of the cloudtrails bucket for logs/queue name for GDA transitions
cloudtrailsbucket: "rcs3-cloudtrails-uci-p-bucket"
s3writetrail: "rcs3-s3-write"
sqs_gda: "rcs3_gda_transitions"

# 4. Where restore reports from Athena queries are stored
reports: "s3://rcs3-godfather-uci-p-bucket"

# 5. Notification for the cloud admin team (region, account, sns-team name)
admin_notify: "rcic-team-notify"
owner_notify: "uci-notify"

# 6. Settings needed to allow end-user to self-service restores
lambda_timeout: 60
lambda_runtime: "python3.12"
lambda_handler: "lambda_function.lambda_handler"
lambda_log_nameprefix: "/aws/lambda/"
lambda_log_retention: 30
s3_glacier_expire: 7

# 7. Restrict service accounts to specific array of IP addresses using
# condition statements in policy definitions. Expected format is d.d.d.d/d
iprestrictions:
  - "128.200.0.0/16"
  - "128.195.0.0/16"
  - "192.5.19.0/24"

#@@@@----------------------------------------------------@@@@
### Following should not be changed localization ###
outputdir: "outputs/"
configfile: "config/aws-admin"
lifecyclejson: "templates/lifecycle-all.json"
commandfile: "templates/ec2-after-boot-commands.txt"
schemafile: "templates/template-athena-schema.txt"
policy_template: "template-policy2.json"

## Alarm Setup
bucket_alarm_templates:
  - object-quota-exceeded.json 
  - excessive-daily-usage.json 
  - space-quota-exceeded.json
  - key-age.json

cloudwatch_dashboard_templates:
  - cost-estimates.json 

## Dashboards made from an array of inner templates 
cloudwatch_dashboard_array:
  - wrapper: cost-estimates-bucket.json
    inner: bucket-storage.json
    replacevar: "%WIDGETS%"
    height: 4
  - wrapper: system-alarms.json
    inner: system-alarm-widget.json
    replacevar: "%WIDGETS%"
    height: 1
    height2: 3
