{
 "title": "UCI - System Alarms",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "dimension_values(us-west-2,AWS/S3/Storage-Lens,StorageBytes,bucket_name)"
   },
   {
    "name": "SDISCOUNT",
    "label": "Storage Discount",
    "query": "0% : 0.00, 18% : 0.18, 45% : 0.45"
   },
   { "name": "EDISCOUNT", "label": "Enterprise Discount", "query": "0% : 0.00, 18% : 0.18" },
   { "name": "S3STD", "query": "0.021" },
   {
    "name": "S3GLACIER",
    "label": "S3 Glacier Class",
    "query": "GLACIER INSTANT : 0.0040, GLACIER FLEXIBLE : 0.0036, GLACIER DEEP : 0.00099"
   },
   { "name": "BYTES2GB", "query": "9.313225746e-10" },
   { "name": "days_in_month", "query": "30" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Quota",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Object Quota",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Request:Object Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "*" },
     "id": "requests",
     "metricName": "AllRequests",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    },
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET" },
     "id": "object_count",
     "metricName": "ObjectCount",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bucket Activity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "SUM([FILL(bucket_req,9), FILL(standard_req,9), FILL(glacier_req,9)])",
     "id": "all_requests",
     "label": "All Requests",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}