---
profile: "166566894905_AWSAdministratorAccess"
accountid: "166566894905"
outputdir: "outputs/"
configfile: "config/aws-admin"
reports: "s3://rcic-godfather-uci"
lifecyclejson: "templates/lifecycle-all.json"
commandfile: "templates/ec2-after-boot-commands.txt"
schemafile: "templates/template-athena-schema.txt"
notify: "arn:aws:sns:us-west-2:774954368688:rcic-team-notify"
## Alarm Setup
region: "us-west-2"
lens: "rcs3-pane"
lensbucket: "rcs3-pane-uci-s-report"
bucket_postfix: "uci-s-bkup-bucket"
inventory_postfix: "uci-s-inventory"
policy_postfix: "uci-bkup-policy"
admin_notify: "rcic-team-notify"
owner_notify: "uci-notify"
bucket_alarm_templates:
  - object-quota-exceeded.json 
  - excessive-daily-usage.json 
  - space-quota-exceeded.json
  - no-activity.json
