profile: "774954368688_AWSAdministratorAccess"
outputdir: "outputs/"
# overrides "AWS_CONFIG_FILE" environment variable if set
# should contain access credentials for the above profile
configfile: "config/aws-admin"