### Settings for the Test Instance RCS3 
---
#@@@@ The following MUST be localized to the AWS Account @@@@ 
profile: "166566894905_AWSAdministratorAccess"
accountid: "166566894905"
region: "us-west-2"

# 1. Where bucket postfixes where backups and inventories are stored
#    policy postfix
bucket_postfix: "uci-s-bkup-bucket"
inventory_postfix: "uci-s-inventory"
policy_postfix: "uci-bkup-policy"

# 2. The name of the storage lens bucket 
lensbucket: "rcs3-pane-uci-s-report"
lens: "rcs3-pane"

# 3. Where restore reports from Athena queries are stored
reports: "s3://rcs3-godfather-uci-s-bucket"

# 4. Notification for the cloud admin team (region, account)
admin_notify: "rcic-team-notify"
owner_notify: "uci-notify"

#@@@@----------------------------------------------------@@@@
### Following should not be changed localization ###
outputdir: "outputs/"
configfile: "config/aws-admin"
lifecyclejson: "templates/lifecycle-all.json"
commandfile: "templates/ec2-after-boot-commands.txt"
schemafile: "templates/template-athena-schema.txt"

## Alarm Setup
bucket_alarm_templates:
  - object-quota-exceeded.json 
  - excessive-daily-usage.json 
  - space-quota-exceeded.json
  - no-activity.json
cloudwatch_dashboard_templates:
  - cost-estimates.json
