profile: "774954368688_AWSAdministratorAccess"
accountid: "774954368688"
outputdir: "outputs/"
configfile: "config/aws-admin"
reports: "s3://rcic-godfather-uci"
lifecyclejson: "templates/lifecycle-all.json"
commandfile: "templates/ec2-after-boot-commands.txt"
schemafile: "templates/template-athena-schema.txt"
