{
 "title": "UCI - Bucket Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "dimension_values(us-west-2,AWS/S3/Storage-Lens,StorageBytes,bucket_name)"
   },
   {
    "name": "SDISCOUNT",
    "label": "Storage Discount",
    "query": "0% : 0.00, 18% : 0.18, 45% : 0.45"
   },
   { "name": "EDISCOUNT", "label": "Enterprise Discount", "query": "0% : 0.00, 18% : 0.18" },
   { "name": "S3STD", "query": "0.021" },
   {
    "name": "S3GLACIER",
    "label": "S3 Glacier Class",
    "query": "GLACIER INSTANT : 0.0040, GLACIER FLEXIBLE : 0.0036, GLACIER DEEP : 0.00099"
   },
   { "name": "BYTES2GB", "query": "9.313225746e-10" },
   { "name": "days_in_month", "query": "30" }
  ]
 },
 "panels": [
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "STANDARD" },
     "id": "standard_bytes",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "GLACIER" },
     "id": "glacier_bytes",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "StorageType": "AllStorageTypes" },
     "id": "object_count",
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Daily Storage Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(1 - $SDISCOUNT) * (((SUM(standard_bytes) * $BYTES2GB / $days_in_month) * $S3STD) + ((SUM(glacier_bytes) * $BYTES2GB / $days_in_month) * $S3GLACIER))",
     "id": "storage_cost",
     "label": "Storage Cost",
     "metricEditorMode": 1,
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "API Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(1-$EDISCOUNT)* ( ((SUM(standard_all) + SUM(glacier_all) - (standard_ppl + glacier_ppl))*.0004/10) + (standard_ppl*.005) + (glacier_ppl*.03) )/1000",
     "id": "api_cost",
     "label": "API Cost",
     "metricEditorMode": 1,
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Standard Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "STANDARD" },
     "id": "standard_bytes",
     "label": "Standard Storage",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Glacier Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "GLACIER" },
     "id": "glacier_bytes",
     "label": "Glacier Storage",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Standard Snapshot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SUM(dm_bytes) + SUM(ncv_bytes)",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Glacier Snapshot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SUM(dm_bytes) + SUM(ncv_bytes)",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "STANDARD" },
     "id": "standard_bytes",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "GLACIER" },
     "id": "glacier_bytes",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "$bucket", "StorageType": "AllStorageTypes" },
     "id": "object_count",
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expression": "(1 - $SDISCOUNT) * (((SUM(standard_bytes) * $BYTES2GB / $days_in_month) * $S3STD) + ((SUM(glacier_bytes) * $BYTES2GB / $days_in_month) * $S3GLACIER))",
     "id": "storage_cost",
     "label": "Storage Cost",
     "metricEditorMode": 1,
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expression": "(1-$EDISCOUNT)* ( ((SUM(standard_all) + SUM(glacier_all) - (standard_ppl + glacier_ppl))*.0004/10) + (standard_ppl*.005) + (glacier_ppl*.03) )/1000",
     "id": "api_cost",
     "label": "API Cost",
     "metricEditorMode": 1,
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "STANDARD" },
     "id": "standard_bytes",
     "label": "Standard Storage",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "bucket_name": "$bucket", "record_type": "BUCKET", "storage_class": "GLACIER" },
     "id": "glacier_bytes",
     "label": "Glacier Storage",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "region": "us-west-2",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expression": "SUM(dm_bytes) + SUM(ncv_bytes)",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expression": "SUM(dm_bytes) + SUM(ncv_bytes)",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}