{
 "title": "UCI - Cost Estimates",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SDISCOUNT",
    "label": "Storage Discount",
    "query": "45% : 0.45,  40% : 0.40, 0% : 0.00"
   },
   {
    "name": "EDISCOUNT",
    "label": "Enterprise Discount",
    "query": "18% : 0.18, 17% : 0.17, 0% : 0.00"
   },
   { "name": "S3STD", "query": "0.021" },
   {
    "name": "S3GLACIER",
    "label": "S3 Glacier Cost",
    "query": "INSTANT : 0.0036, FLEXIBLE : 0.0040"
   },
   { "name": "S3DEEP", "query": "0.00099" },
   {
    "name": "BYTES2GB",
    "query": "9.313225746e-10 : 9.313225746e-10"
   },
   { "name": "days_in_month", "query": "30" },
   { "name": "region", "query": "us-west-2" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Archive Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Standard Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Object Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "record_type": "ACCOUNT" },
     "metricName": "ObjectCount",
     "namespace": "AWS/S3/Storage-Lens",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Daily Storage Cost Avg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Snapshot bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "record_type": "ACCOUNT" },
     "metricName": "NonCurrentVersionStorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    },
    {
     "dimensions": { "record_type": "ACCOUNT" },
     "metricName": "DeleteMarkerStorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Snapshot Overhead",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "API Costs 2 (Enhanced - No Glacier)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "SUM([standard_all, deep_all, bucket_all])",
     "id": "all_requests",
     "label": "All Requests",
     "metricEditorMode": 1,
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "expression": "(1-$EDISCOUNT) * (((all_requests - (standard_bucket_ppl + deep_ppl)) * 0.0004) + (standard_bucket_ppl * 0.005) + (deep_ppl * 0.05)) / 1000",
     "id": "api_cost",
     "label": "API Cost (Enhanced)",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    },
    {
     "expression": "RUNNING_SUM(api_cost)",
     "id": "api_cost_sum",
     "label": "Cumulative API Cost",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Costs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "record_type": "ACCOUNT", "storage_class": "STANDARD" },
     "id": "s_bytes",
     "label": "STANDARD",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Sum"
    },
    {
     "dimensions": { "record_type": "ACCOUNT", "storage_class": "DEEP_ARCHIVE" },
     "id": "d_bytes",
     "label": "DEEP_ARCHIVE",
     "metricName": "StorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "${region}",
     "statistic": "Sum"
    },
    {
     "expression": "((SUM(s_bytes) * $BYTES2GB / $days_in_month) * $S3STD * (1 - $SDISCOUNT)) + ((SUM(d_bytes) * $BYTES2GB / $days_in_month) * $S3DEEP)",
     "id": "daily_storage_cost",
     "label": "Daily Storage Cost",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "expression": "RUNNING_SUM(daily_storage_cost)",
     "id": "total_cost",
     "label": "Total Cost",
     "metricEditorMode": 1,
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "record_type": "ACCOUNT" },
     "id": "ncv_sbytes",
     "metricName": "NonCurrentVersionStorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "record_type": "ACCOUNT" },
     "id": "dm_sbytes",
     "metricName": "DeleteMarkerStorageBytes",
     "namespace": "AWS/S3/Storage-Lens",
     "period": "86400",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}